RAW_DATA_PATH = "data/raw_pdfs"
CLEANED_PATH = "data/cleaned_text"
CHUNKS_PATH = "data/chunks"

CHUNK_SIZE = 512  # tokens
CHUNK_OVERLAP = 50

# --- RAG Settings ---
K_RETRIEVAL = 20
K_RERANK = 8
K_DEFAULT = 12
TEMPERATURE = 0.1
RERANKER_MODEL = "cross-encoder/ms-marco-MiniLM-L-6-v2"
USE_HYBRID_RETRIEVAL = True
HYBRID_DENSE_CANDIDATES = 80
HYBRID_BM25_CANDIDATES = 80
HYBRID_RRF_K = 60
HYBRID_DENSE_WEIGHT = 1.0
HYBRID_BM25_WEIGHT = 1.0
MIN_GATHERING_QUESTIONS = 15
EXTRA_GATHERING_QUESTIONS_IF_UNCERTAIN = 5

HEADER_FOOTER_THRESHOLD = 0.7
