RAW_DATA_PATH = "data/raw_pdfs"
CLEANED_PATH = "data/cleaned_text"
CHUNKS_PATH = "data/chunks"

CHUNK_SIZE = 512  # tokens
CHUNK_OVERLAP = 50

# --- RAG Settings ---
K_RETRIEVAL = 20
K_RERANK = 8
K_DEFAULT = 12
TEMPERATURE = 0.1
RERANKER_MODEL = "cross-encoder/ms-marco-MiniLM-L-6-v2"
USE_HYBRID_RETRIEVAL = True
HYBRID_DENSE_CANDIDATES = 80
HYBRID_BM25_CANDIDATES = 80
HYBRID_RRF_K = 60
HYBRID_DENSE_WEIGHT = 1.0
HYBRID_BM25_WEIGHT = 1.0
MIN_GATHERING_QUESTIONS = 10
EXTRA_GATHERING_QUESTIONS_IF_UNCERTAIN = 3
DIAGNOSIS_CONFIDENCE_THRESHOLD = 0.70
MAX_REMEDY_INTERVENTIONS = 3
ENABLE_CONSERVATIVE_FIRST_POLICY = True
ENABLE_TREATMENT_RISK_GATE = True
VERIFY_ALL_CASES = False
MAX_VERIFICATION_TARGETED_QUESTIONS = 3
MAX_VERIFICATION_REFINEMENT_CYCLES = 2
AUTO_PRINT_REMEDIES_AFTER_VERIFIED_DIAGNOSIS = True

HEADER_FOOTER_THRESHOLD = 0.7

# --- Conversation/Safety behavior ---
PEDIATRIC_AGE_THRESHOLD = 18
PEDIATRIC_ESCALATION_ENABLED = True
MINOR_SWELLING_KEYWORDS = [
    "swelling",
    "edema",
    "oedema",
    "pitting",
]
LOWER_LIMB_KEYWORDS = [
    "leg",
    "ankle",
    "foot",
    "feet",
    "calf",
]
PEDIATRIC_SYSTEMIC_RISK_KEYWORDS = [
    "fever",
    "breathlessness",
    "shortness of breath",
    "chest pain",
    "reduced urine",
    "dark urine",
]
