# src/rag/ollama_verifier.py

import json
import requests

OLLAMA_VERIFIER_PROMPT = """
You are a Medical Consistency Auditor for an Ayurvedic RAG system.
The following diagnosis was generated by a Bayesian reasoning engine. 
Your task is to verify it against the provided context and symptoms.

USER SYMPTOMS:
{user_symptoms}

BAYESIAN DIAGNOSIS:
{diagnosis_report}

KNOWLEDGE CONTEXT (BOOKS):
{retrieved_chunks}

TASK:
Check for:
1. MISSING SYMPTOMS: Are there critical symptoms for this disease mentioned in the books but not observed in the user?
2. CONTRADICTIONS: Does the user have a symptom that explicitly rules out this disease according to textbooks?
3. SAFETY: Are there red flags (black stool, fainting, high fever) that require immediate escalation?
4. RARE CONDITIONS: Could this be a rare condition that the Bayesian model might overlook?

Return ONLY valid JSON:
{{
  "is_consistent": true/false,
  "contradictions_found": ["list of contradictions or empty"],
  "missing_critical_symptoms": ["list of symptoms or empty"],
  "safety_risk_level": "low/medium/high/critical",
  "auditor_notes": "brief explanation"
}}
"""

class OllamaVerifier:
    def __init__(self, model_name="llama3"):
        self.url = "http://localhost:11434/api/generate"
        self.model = model_name

    def verify(self, user_symptoms, diagnosis_report, retrieved_chunks):
        prompt = OLLAMA_VERIFIER_PROMPT.format(
            user_symptoms=json.dumps(user_symptoms, indent=2),
            diagnosis_report=diagnosis_report,
            retrieved_chunks="\n\n".join([c['text'] for c in retrieved_chunks[:3]])
        )

        try:
            response = requests.post(
                self.url,
                json={
                    "model": self.model,
                    "prompt": prompt,
                    "stream": False,
                    "format": "json"
                },
                timeout=30
            )
            
            if response.status_code == 200:
                result = response.json().get("response", "{}")
                return json.loads(result)
            return {"is_consistent": True, "safety_risk_level": "medium", "auditor_notes": "Ollama connection failed"}
            
        except Exception as e:
            print(f"[Ollama Verifier Error: {e}]")
            return {"is_consistent": True, "safety_risk_level": "medium", "auditor_notes": str(e)}
